### ISSUE TITLE
Problems about training Deraining

### ISSUE THREAD

**Issue by Luckywlp** [swz30/Restormer#28]
Hi,Congratulations to you have a good job!
Although I haved changed the number of GPUs in  **train.sh**  and  **Deraining_Restormer.yml**  to 4 since I only have 4 GPUs，I can't train the code of Deraining due to my GPU memory limitations. I found the program can run if I change the  **batch_size_per_gpu**  smaller. But the batch size can't meet the experimental settings.
So what can I do if I want to achieve the settings in your experiment ( i.e. For progressive learning, we start training with patch size 128×128 and batch size 64. The patch size and batch size pairs are updated to [(160^2,40), (192^2,32), (256^2,16), (320^2,8),(384^2,8)] at iterations [92K, 156K, 204K, 240K, 276K].) ?

**Comment by swz30** [comment]
Hi @Luckywlp,

You can adjust the batch size according to your available resources. Then you increase the total number of training iterations (e.g. 500K) such that the number of examples seen by the network in your setting is more or less similar to ours. Hopefully, this will reproduce the performance reported in the paper.

**Comment by Luckywlp** [comment]
> Hi @Luckywlp,
> 
> You can adjust the batch size according to your available resources. Then you increase the total number of training iterations (e.g. 500K) such that the number of examples seen by the network in your setting is more or less similar to ours. Hopefully, this will reproduce the performance reported in the paper.

**Comment by Luckywlp** [comment]
> Hi @Luckywlp,
> 
> You can adjust the batch size according to your available resources. Then you increase the total number of training iterations (e.g. 500K) such that the number of examples seen by the network in your setting is more or less similar to ours. Hopefully, this will reproduce the performance reported in the paper.

**Comment by Luckywlp** [comment]
Thanks for your reply! 
My machine has only 4 GPUs, and the maximum **batch_size_per_gpu** can only be set to 3. Can you give me a more specific reference setting for  progressive learning？
Looking forward to your reply

**Comment by swz30** [comment]
Hi @Luckywlp,

Here is an example setting (though I am not sure about the final performance):

```
datasets:
  train:
    gt_size: 320
    gt_sizes: [64,96,128,160,192,256,320]

    num_worker_per_gpu: 8
    batch_size_per_gpu: 4
    mini_batch_sizes: [6,4,3,2,2,1,1]
    iters: [172000,128000,104000,72000,52000,40000,32000]

train:
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [300000, 300000]
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]
  total_iter: 600000

```
Note that I have added smaller patch sizes (64,96) and more iterations at the beginning, this will help speed up the training. Also, make sure to check (and adjust if needed) that your GPUs can handle all these patch-size and batch-size pairs before you run the full training.
